### ISSUE TITLE
页面开始就报token错误

### ISSUE THREAD

**Issue by xingfeng1234** [zyqwst/DayBookApp#2]
![image](https://user-images.githubusercontent.com/5634750/32833636-72bd3c50-ca3a-11e7-93fa-d60dfeecc0db.png)
是不是某个地方得设置，现在报令牌错误。

**Comment by zyqwst** [comment]
这个是我的疏忽，在http-service.ts里面 的方法，没有做user的判断
public getToken():string{
        let user = this.getCurrUser(); 
        if(user==null){this.alert('Token错误，请登录后重试');}
        let token = user.id+"_"+user.token;
        return token;
    }
